name: ci

on:
  pull_request:
    branches: [main]

jobs:
  selenium:
    strategy:
      matrix:
        os: [macos-12, ubuntu-22.04, windows-2022]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.1
      - name: Use Node version defined in manifest
        uses: volta-cli/action@v4
      - name: Node.js version
        run: node -v
      - name: npm version
        run: npm -v
      - name: Setup Python
        uses: actions/setup-python@v4.6.1
        with:
          python-version: "3.11.0"
          cache: pip
      - name: Install Node dependencies
        run: npm ci
      - name: Install Python dependencies
        run: python3 -m pipenv install
      - name: Run Selenium test suite
        run: python3 -m pytest test.py
